# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Create_Source.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(987, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 10, 871, 531))
        self.frame.setStyleSheet("QFrame{\n"
"background:rgb(201, 176, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.NAME = QtWidgets.QComboBox(self.frame)
        self.NAME.setGeometry(QtCore.QRect(100, 140, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.NAME.setFont(font)
        self.NAME.setObjectName("NAME")
        self.NAME.addItem("")
        self.NAME.addItem("")
        self.NAME.addItem("")
        self.NAME.addItem("")
        self.NAME.addItem("")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 140, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(710, 140, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(270, 140, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(self.frame)
        self.spinBox.setGeometry(QtCore.QRect(760, 140, 51, 41))
        self.spinBox.setObjectName("spinBox")
        self.NAME_2 = QtWidgets.QComboBox(self.frame)
        self.NAME_2.setGeometry(QtCore.QRect(320, 140, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.NAME_2.setFont(font)
        self.NAME_2.setObjectName("NAME_2")
        self.NAME_2.addItem("")
        self.NAME_2.addItem("")
        self.NAME_2.addItem("")
        self.NAME_2.addItem("")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(490, 140, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.NAME_3 = QtWidgets.QComboBox(self.frame)
        self.NAME_3.setGeometry(QtCore.QRect(540, 140, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.NAME_3.setFont(font)
        self.NAME_3.setObjectName("NAME_3")
        self.NAME_3.addItem("")
        self.NAME_3.addItem("")
        self.NAME_3.addItem("")
        self.NAME_3.addItem("")
        self.NAME_3.addItem("")
        self.NAME_3.addItem("")
        self.NAME_3.addItem("")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(270, 200, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(490, 200, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(710, 200, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame)
        self.spinBox_2.setGeometry(QtCore.QRect(760, 200, 51, 41))
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(30, 260, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(270, 260, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(490, 260, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(710, 260, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame)
        self.spinBox_3.setGeometry(QtCore.QRect(760, 260, 51, 41))
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(30, 320, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(270, 320, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(490, 320, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(710, 320, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.spinBox_4 = QtWidgets.QSpinBox(self.frame)
        self.spinBox_4.setGeometry(QtCore.QRect(760, 320, 51, 41))
        self.spinBox_4.setObjectName("spinBox_4")
        self.NAME_4 = QtWidgets.QComboBox(self.frame)
        self.NAME_4.setGeometry(QtCore.QRect(100, 200, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.NAME_4.setFont(font)
        self.NAME_4.setObjectName("NAME_4")
        self.NAME_4.addItem("")
        self.NAME_4.addItem("")
        self.NAME_4.addItem("")
        self.NAME_4.addItem("")
        self.NAME_4.addItem("")
        self.NAME_7 = QtWidgets.QComboBox(self.frame)
        self.NAME_7.setGeometry(QtCore.QRect(100, 260, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.NAME_7.setFont(font)
        self.NAME_7.setObjectName("NAME_7")
        self.NAME_7.addItem("")
        self.NAME_7.addItem("")
        self.NAME_7.addItem("")
        self.NAME_7.addItem("")
        self.NAME_7.addItem("")
        self.NAME_10 = QtWidgets.QComboBox(self.frame)
        self.NAME_10.setGeometry(QtCore.QRect(100, 320, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.NAME_10.setFont(font)
        self.NAME_10.setObjectName("NAME_10")
        self.NAME_10.addItem("")
        self.NAME_10.addItem("")
        self.NAME_10.addItem("")
        self.NAME_10.addItem("")
        self.NAME_10.addItem("")
        self.NAME_13 = QtWidgets.QComboBox(self.frame)
        self.NAME_13.setGeometry(QtCore.QRect(320, 200, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.NAME_13.setFont(font)
        self.NAME_13.setObjectName("NAME_13")
        self.NAME_13.addItem("")
        self.NAME_13.addItem("")
        self.NAME_13.addItem("")
        self.NAME_13.addItem("")
        self.NAME_14 = QtWidgets.QComboBox(self.frame)
        self.NAME_14.setGeometry(QtCore.QRect(320, 260, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.NAME_14.setFont(font)
        self.NAME_14.setObjectName("NAME_14")
        self.NAME_14.addItem("")
        self.NAME_14.addItem("")
        self.NAME_14.addItem("")
        self.NAME_14.addItem("")
        self.NAME_15 = QtWidgets.QComboBox(self.frame)
        self.NAME_15.setGeometry(QtCore.QRect(320, 320, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.NAME_15.setFont(font)
        self.NAME_15.setObjectName("NAME_15")
        self.NAME_15.addItem("")
        self.NAME_15.addItem("")
        self.NAME_15.addItem("")
        self.NAME_15.addItem("")
        self.NAME_5 = QtWidgets.QComboBox(self.frame)
        self.NAME_5.setGeometry(QtCore.QRect(540, 200, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.NAME_5.setFont(font)
        self.NAME_5.setObjectName("NAME_5")
        self.NAME_5.addItem("")
        self.NAME_5.addItem("")
        self.NAME_5.addItem("")
        self.NAME_5.addItem("")
        self.NAME_5.addItem("")
        self.NAME_5.addItem("")
        self.NAME_5.addItem("")
        self.NAME_6 = QtWidgets.QComboBox(self.frame)
        self.NAME_6.setGeometry(QtCore.QRect(540, 260, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.NAME_6.setFont(font)
        self.NAME_6.setObjectName("NAME_6")
        self.NAME_6.addItem("")
        self.NAME_6.addItem("")
        self.NAME_6.addItem("")
        self.NAME_6.addItem("")
        self.NAME_6.addItem("")
        self.NAME_6.addItem("")
        self.NAME_6.addItem("")
        self.NAME_8 = QtWidgets.QComboBox(self.frame)
        self.NAME_8.setGeometry(QtCore.QRect(540, 320, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.NAME_8.setFont(font)
        self.NAME_8.setObjectName("NAME_8")
        self.NAME_8.addItem("")
        self.NAME_8.addItem("")
        self.NAME_8.addItem("")
        self.NAME_8.addItem("")
        self.NAME_8.addItem("")
        self.NAME_8.addItem("")
        self.NAME_8.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(360, 420, 181, 81))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 987, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NAME.setItemText(0, _translate("MainWindow", "软件工程"))
        self.NAME.setItemText(1, _translate("MainWindow", "机器学习"))
        self.NAME.setItemText(2, _translate("MainWindow", "人工智能"))
        self.NAME.setItemText(3, _translate("MainWindow", "系统综合"))
        self.NAME.setItemText(4, _translate("MainWindow", "体系结构"))
        self.label.setText(_translate("MainWindow", "名称"))
        self.label_2.setText(_translate("MainWindow", "课时"))
        self.label_3.setText(_translate("MainWindow", "类别"))
        self.NAME_2.setItemText(0, _translate("MainWindow", "专业必修课"))
        self.NAME_2.setItemText(1, _translate("MainWindow", "公共必修课"))
        self.NAME_2.setItemText(2, _translate("MainWindow", "专业选修课"))
        self.NAME_2.setItemText(3, _translate("MainWindow", "公共选修课"))
        self.label_4.setText(_translate("MainWindow", "教室"))
        self.NAME_3.setItemText(0, _translate("MainWindow", "302-106"))
        self.NAME_3.setItemText(1, _translate("MainWindow", "302-201"))
        self.NAME_3.setItemText(2, _translate("MainWindow", "302-202"))
        self.NAME_3.setItemText(3, _translate("MainWindow", "302-203"))
        self.NAME_3.setItemText(4, _translate("MainWindow", "302-206"))
        self.NAME_3.setItemText(5, _translate("MainWindow", "302-503"))
        self.NAME_3.setItemText(6, _translate("MainWindow", "306-704"))
        self.label_5.setText(_translate("MainWindow", "名称"))
        self.label_6.setText(_translate("MainWindow", "类别"))
        self.label_7.setText(_translate("MainWindow", "教室"))
        self.label_8.setText(_translate("MainWindow", "课时"))
        self.label_9.setText(_translate("MainWindow", "名称"))
        self.label_10.setText(_translate("MainWindow", "类别"))
        self.label_11.setText(_translate("MainWindow", "教室"))
        self.label_12.setText(_translate("MainWindow", "课时"))
        self.label_13.setText(_translate("MainWindow", "名称"))
        self.label_14.setText(_translate("MainWindow", "类别"))
        self.label_15.setText(_translate("MainWindow", "教室"))
        self.label_16.setText(_translate("MainWindow", "课时"))
        self.NAME_4.setItemText(0, _translate("MainWindow", "软件工程"))
        self.NAME_4.setItemText(1, _translate("MainWindow", "机器学习"))
        self.NAME_4.setItemText(2, _translate("MainWindow", "人工智能"))
        self.NAME_4.setItemText(3, _translate("MainWindow", "系统综合"))
        self.NAME_4.setItemText(4, _translate("MainWindow", "体系结构"))
        self.NAME_7.setItemText(0, _translate("MainWindow", "软件工程"))
        self.NAME_7.setItemText(1, _translate("MainWindow", "机器学习"))
        self.NAME_7.setItemText(2, _translate("MainWindow", "人工智能"))
        self.NAME_7.setItemText(3, _translate("MainWindow", "系统综合"))
        self.NAME_7.setItemText(4, _translate("MainWindow", "体系结构"))
        self.NAME_10.setItemText(0, _translate("MainWindow", "软件工程"))
        self.NAME_10.setItemText(1, _translate("MainWindow", "机器学习"))
        self.NAME_10.setItemText(2, _translate("MainWindow", "人工智能"))
        self.NAME_10.setItemText(3, _translate("MainWindow", "系统综合"))
        self.NAME_10.setItemText(4, _translate("MainWindow", "体系结构"))
        self.NAME_13.setItemText(0, _translate("MainWindow", "专业必修课"))
        self.NAME_13.setItemText(1, _translate("MainWindow", "公共必修课"))
        self.NAME_13.setItemText(2, _translate("MainWindow", "专业选修课"))
        self.NAME_13.setItemText(3, _translate("MainWindow", "公共选修课"))
        self.NAME_14.setItemText(0, _translate("MainWindow", "专业必修课"))
        self.NAME_14.setItemText(1, _translate("MainWindow", "公共必修课"))
        self.NAME_14.setItemText(2, _translate("MainWindow", "专业选修课"))
        self.NAME_14.setItemText(3, _translate("MainWindow", "公共选修课"))
        self.NAME_15.setItemText(0, _translate("MainWindow", "专业必修课"))
        self.NAME_15.setItemText(1, _translate("MainWindow", "公共必修课"))
        self.NAME_15.setItemText(2, _translate("MainWindow", "专业选修课"))
        self.NAME_15.setItemText(3, _translate("MainWindow", "公共选修课"))
        self.NAME_5.setItemText(0, _translate("MainWindow", "302-106"))
        self.NAME_5.setItemText(1, _translate("MainWindow", "302-201"))
        self.NAME_5.setItemText(2, _translate("MainWindow", "302-202"))
        self.NAME_5.setItemText(3, _translate("MainWindow", "302-203"))
        self.NAME_5.setItemText(4, _translate("MainWindow", "302-206"))
        self.NAME_5.setItemText(5, _translate("MainWindow", "302-503"))
        self.NAME_5.setItemText(6, _translate("MainWindow", "306-704"))
        self.NAME_6.setItemText(0, _translate("MainWindow", "302-106"))
        self.NAME_6.setItemText(1, _translate("MainWindow", "302-201"))
        self.NAME_6.setItemText(2, _translate("MainWindow", "302-202"))
        self.NAME_6.setItemText(3, _translate("MainWindow", "302-203"))
        self.NAME_6.setItemText(4, _translate("MainWindow", "302-206"))
        self.NAME_6.setItemText(5, _translate("MainWindow", "302-503"))
        self.NAME_6.setItemText(6, _translate("MainWindow", "306-704"))
        self.NAME_8.setItemText(0, _translate("MainWindow", "302-106"))
        self.NAME_8.setItemText(1, _translate("MainWindow", "302-201"))
        self.NAME_8.setItemText(2, _translate("MainWindow", "302-202"))
        self.NAME_8.setItemText(3, _translate("MainWindow", "302-203"))
        self.NAME_8.setItemText(4, _translate("MainWindow", "302-206"))
        self.NAME_8.setItemText(5, _translate("MainWindow", "302-503"))
        self.NAME_8.setItemText(6, _translate("MainWindow", "306-704"))
        self.pushButton.setText(_translate("MainWindow", "生成课表"))
